Interface:

    TextInput:
        id:first_textinput
        multiline:False
        size_hint:0.5,0.1
        pos_hint:{"center_x":0.5,"center_y":0.6}
    Label:
        id:first_label
        text:""
        size_hint:0.5,0.1
        pos_hint:{"center_x":0.5,"center_y":0.5}
    Button:
        text:"Click Me!"
        size_hint:0.5,0.1
        pos_hint:{"center_x":0.5,"center_y":0.4}
        on_press: root.button_clicked()

